groups:
- name: alert.rules
  rules:
  - alert: containerAlert
    expr: absent(((time() - container_last_seen{name="ping"}) < 5))
    for: 5s
    labels:
      service: backend
      severity: critical
    annotations:
      DESCRIPTION: Container Instance is down for more than 15 sec.
      SUMMARY: Container Instance down
  - alert: HighCPU
    expr: ((sum by(instance, job) (node_cpu{mode=~"user|nice|system|irq|softirq|steal|idle|iowait"}))
      - (sum by(instance, job) (node_cpu{mode=~"idle|iowait"}))) / (sum by(instance,
      job) (node_cpu{mode=~"user|nice|system|irq|softirq|steal|idle|iowait"})) * 100
      > 95
    for: 10m
    labels:
      service: backend
      severity: warning
    annotations:
      description: This machine has really high CPU usage for over 10m
      summary: High CPU Usage
  - alert: DiskWillFillIn4Hours
    expr: predict_linear(node_filesystem_free{job="prometheus"}[1h], 4 * 3600) < 0
    for: 5m
    labels:
      severity: critical
